### ISSUE TITLE
Help on coMD

### ISSUE THREAD

**Issue by rakeshr10** [prody/coMD#1]
Hi, 
  I have been trying to run coMD with the old version which is available at this site (http://csb.pitt.edu/coMD/). However I am unable to figure out how to use it for my system of interest and get it running. I did write to Mert Gur as mentioned in the website but did not get any response. I would be grateful if you could help me on this.

   1) I see in your shell script that the jobs are submitted simultaneously and queued. So my doubt is can the jobs be run serially one by one that is 1 to 10, 10 to 20 etc. This is because my computing resources are limited and I would like to know if the trajectories are interchanged among the folders as in umbrella sampling.

   2) One of my states has Mg ion bound, so should this also be taken into account while the conformations are modelled.

   3) Moreover how do I know decide the number of cycles and it has converged.

   I am also an extensive user of ProDy, so does ProDy have the capability to perform protein-RNA + ions (ligand) ANM as in ANM 2.0 webserver. Also as I noticed in your github page that coMD is being implemented using ProDy, I would like to try even if it is in beta release.

**Comment by jamesmkrieger** [comment]
Hi,

Sorry no one has answered you and it's been such a while. I'm now working on this so here's some replies. Hopefully it's not so long that you no longer care.

1. There is no interaction between runs in a way similar to replica exchange (which I assume is what you mean rather than umbrella sampling) but the runs in opposite directions are supposed to converge to a common intermediate so run 2 requires the result of run 20 and run 19 requires the result of run 1. You could in theory do run 1 then run 20 then run 2 then run 19 and so on. It would only require a small change in the tcl code I think. You'd want to add a "wait" command like line 975 to line after lines 971 (initial minimization), 1132 (production/TMD) and 1249 (final minimization). 

2. Yes, you do want to include the Mg ion. The current coMD version doesn't allow this I think but it should be possible by deleting "protein and" on lines 636, 640, 703 and 707. I also realised that 636 and 640 are redundant and 703 and 707 are redundant and combined them in my version. You can check the current pull request (#2) for my changes.

3. I don't know. Is there not a check for convergence in coMD already?

I don't think you can use coMD straight from within ProDy because there are tcl bits. What was meant is that is part of the overall ProDy project in the same way as NMWiz and DruGUI. As for RNA and ions, you should be able to use them for ANM in ProDy by defining what nodes to use for building the Hessian I think but I haven't really tried.

Best wishes
James

**Comment by jamesmkrieger** [comment]
I am assuming this isn't relevant to you any more (especially seeing as you haven't replied) so I'm closing this issue.

Just a brief note: the current version does support including things that aren't proteins as long as you set which chains you want. If you don't set chains it takes all protein parts.

As for convergence, the run should stop (hit a break) when the two endpoints get within a certain RMSD.

**Comment by rakeshr10** [comment]
Sorry for not replying earlier. Thanks for the inputs. Currently I am not using coMD but might use it in the near future. Will get back to you if I have issues.

**Comment by jamesmkrieger** [comment]
Ok. You’re welcome. Happy to help with whatever issues you may have. I’m now actively working on this and it’s good to know another person is interested
